### ISSUE TITLE
icon shortcuts are too easy to typo

### ISSUE THREAD

**Issue by sagargp** [sagargp/trollicons#9] opened 2011-04-14 19:45 UTC
for example:

Me: hey bro [friends[
Me: damnit, [friends*
Me: [friends[]***
Me: ![](https://github.com/sagargp/trollicons/raw/master/Icons/Rage/Intense-fu2-rage2.png)

I propose a new system where for each [rage] we also support /rage or something similar. Maybe even [rage and [rage[ are caught too, so we avoid those stupid typos.

**Comment by paradox460** [comment] 2011-04-30 08:10
Yes, i've been having these irritating typos. So…fucking…irritating.

**Comment by unregistered** [comment] 2011-04-30 08:45
Fork and patch human nature?

**Comment by paradox460** [comment] 2011-06-18 23:49
I've figured out a solution, and i'll make a branch with it.

**Comment by unregistered** [comment] 2012-07-01 21:31
Duplicate of #24

**Closed as completed by unregistered** 2012-07-01 21:31 UTC
